# Generated by Django 6.0.8 on 2026-09-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectgrant",
            name="relation_oid",
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
    ]
