# Generated by Django 6.0.8 on 2026-09-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0002_objectgrant_relation_oid"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="objectgrant",
            name="role_object_unique",
        ),
        migrations.AddConstraint(
            model_name="objectgrant",
            constraint=models.UniqueConstraint(
                fields=("role", "relation_oid"), name="role_relation_unique"
            ),
        ),
    ]
