# Generated by Django 6.0.8 on 2026-09-14 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0003_remove_objectgrant_role_object_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrole",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                validators=[django.core.validators.MaxLengthValidator(2000)],
            ),
        ),
        migrations.AddField(
            model_name="personaldatabase",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
    ]
